version: '3'
services:
  anaconda3:
    container_name: shift-python
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/notebooks
    build:
      context: ./
      dockerfile: Dockerfile
